// Generated by scripts/build-countries.mjs — do not edit by hand.
// Country data © Mohammed Le Doze, ODbL 1.0 (https://github.com/mledoze/countries).
import type { Country } from "./types";

export const COUNTRIES: Country[] = [
  {
    "code": "AF",
    "name": "Afghanistan",
    "capital": "Kabul",
    "region": "Asia",
    "subregion": "Southern Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "AL",
    "name": "Albania",
    "capital": "Tirana",
    "region": "Europe",
    "subregion": "Southeast Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "DZ",
    "name": "Algeria",
    "capital": "Algiers",
    "region": "Africa",
    "subregion": "Northern Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "AD",
    "name": "Andorra",
    "capital": "Andorra la Vella",
    "region": "Europe",
    "subregion": "Southern Europe",
    "tier": 2,
    "capitalQuestions": false
  },
  {
    "code": "AO",
    "name": "Angola",
    "capital": "Luanda",
    "region": "Africa",
    "subregion": "Middle Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "AG",
    "name": "Antigua and Barbuda",
    "capital": "St. John's",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "AR",
    "name": "Argentina",
    "capital": "Buenos Aires",
    "region": "Americas",
    "subregion": "South America",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "AM",
    "name": "Armenia",
    "capital": "Yerevan",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "AU",
    "name": "Australia",
    "capital": "Canberra",
    "region": "Oceania",
    "subregion": "Australia and New Zealand",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "AT",
    "name": "Austria",
    "capital": "Vienna",
    "region": "Europe",
    "subregion": "Central Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "AZ",
    "name": "Azerbaijan",
    "capital": "Baku",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "BS",
    "name": "Bahamas",
    "capital": "Nassau",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "BH",
    "name": "Bahrain",
    "capital": "Manama",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "BD",
    "name": "Bangladesh",
    "capital": "Dhaka",
    "region": "Asia",
    "subregion": "Southern Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "BB",
    "name": "Barbados",
    "capital": "Bridgetown",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "BY",
    "name": "Belarus",
    "capital": "Minsk",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "BE",
    "name": "Belgium",
    "capital": "Brussels",
    "region": "Europe",
    "subregion": "Western Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "BZ",
    "name": "Belize",
    "capital": "Belmopan",
    "region": "Americas",
    "subregion": "Central America",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "BJ",
    "name": "Benin",
    "capital": "Porto-Novo",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "BT",
    "name": "Bhutan",
    "capital": "Thimphu",
    "region": "Asia",
    "subregion": "Southern Asia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "BO",
    "name": "Bolivia",
    "capital": "Sucre",
    "region": "Americas",
    "subregion": "South America",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "BA",
    "name": "Bosnia and Herzegovina",
    "capital": "Sarajevo",
    "region": "Europe",
    "subregion": "Southeast Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "BW",
    "name": "Botswana",
    "capital": "Gaborone",
    "region": "Africa",
    "subregion": "Southern Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "BR",
    "name": "Brazil",
    "capital": "Brasília",
    "region": "Americas",
    "subregion": "South America",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "BN",
    "name": "Brunei",
    "capital": "Bandar Seri Begawan",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "BG",
    "name": "Bulgaria",
    "capital": "Sofia",
    "region": "Europe",
    "subregion": "Southeast Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "BF",
    "name": "Burkina Faso",
    "capital": "Ouagadougou",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "BI",
    "name": "Burundi",
    "capital": "Gitega",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "KH",
    "name": "Cambodia",
    "capital": "Phnom Penh",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "CM",
    "name": "Cameroon",
    "capital": "Yaoundé",
    "region": "Africa",
    "subregion": "Middle Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "CA",
    "name": "Canada",
    "capital": "Ottawa",
    "region": "Americas",
    "subregion": "North America",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "CV",
    "name": "Cape Verde",
    "capital": "Praia",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "CF",
    "name": "Central African Republic",
    "capital": "Bangui",
    "region": "Africa",
    "subregion": "Middle Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "TD",
    "name": "Chad",
    "capital": "N'Djamena",
    "region": "Africa",
    "subregion": "Middle Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "CL",
    "name": "Chile",
    "capital": "Santiago",
    "region": "Americas",
    "subregion": "South America",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "CN",
    "name": "China",
    "capital": "Beijing",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "CO",
    "name": "Colombia",
    "capital": "Bogotá",
    "region": "Americas",
    "subregion": "South America",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "KM",
    "name": "Comoros",
    "capital": "Moroni",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "CR",
    "name": "Costa Rica",
    "capital": "San José",
    "region": "Americas",
    "subregion": "Central America",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "CI",
    "name": "Côte d'Ivoire",
    "capital": "Yamoussoukro",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "HR",
    "name": "Croatia",
    "capital": "Zagreb",
    "region": "Europe",
    "subregion": "Southeast Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "CU",
    "name": "Cuba",
    "capital": "Havana",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "CY",
    "name": "Cyprus",
    "capital": "Nicosia",
    "region": "Europe",
    "subregion": "Southern Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "CZ",
    "name": "Czechia",
    "capital": "Prague",
    "region": "Europe",
    "subregion": "Central Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "DK",
    "name": "Denmark",
    "capital": "Copenhagen",
    "region": "Europe",
    "subregion": "Northern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "DJ",
    "name": "Djibouti",
    "capital": "Djibouti",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 3,
    "capitalQuestions": false
  },
  {
    "code": "DM",
    "name": "Dominica",
    "capital": "Roseau",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "DO",
    "name": "Dominican Republic",
    "capital": "Santo Domingo",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "CD",
    "name": "DR Congo",
    "capital": "Kinshasa",
    "region": "Africa",
    "subregion": "Middle Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "EC",
    "name": "Ecuador",
    "capital": "Quito",
    "region": "Americas",
    "subregion": "South America",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "EG",
    "name": "Egypt",
    "capital": "Cairo",
    "region": "Africa",
    "subregion": "Northern Africa",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "SV",
    "name": "El Salvador",
    "capital": "San Salvador",
    "region": "Americas",
    "subregion": "Central America",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "GQ",
    "name": "Equatorial Guinea",
    "capital": "Malabo",
    "region": "Africa",
    "subregion": "Middle Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "ER",
    "name": "Eritrea",
    "capital": "Asmara",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "EE",
    "name": "Estonia",
    "capital": "Tallinn",
    "region": "Europe",
    "subregion": "Northern Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "SZ",
    "name": "Eswatini",
    "capital": "Mbabane",
    "region": "Africa",
    "subregion": "Southern Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "ET",
    "name": "Ethiopia",
    "capital": "Addis Ababa",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "FJ",
    "name": "Fiji",
    "capital": "Suva",
    "region": "Oceania",
    "subregion": "Melanesia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "FI",
    "name": "Finland",
    "capital": "Helsinki",
    "region": "Europe",
    "subregion": "Northern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "FR",
    "name": "France",
    "capital": "Paris",
    "region": "Europe",
    "subregion": "Western Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "GA",
    "name": "Gabon",
    "capital": "Libreville",
    "region": "Africa",
    "subregion": "Middle Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "GM",
    "name": "Gambia",
    "capital": "Banjul",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "GE",
    "name": "Georgia",
    "capital": "Tbilisi",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "DE",
    "name": "Germany",
    "capital": "Berlin",
    "region": "Europe",
    "subregion": "Western Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "GH",
    "name": "Ghana",
    "capital": "Accra",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "GR",
    "name": "Greece",
    "capital": "Athens",
    "region": "Europe",
    "subregion": "Southern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "GD",
    "name": "Grenada",
    "capital": "St. George's",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "GT",
    "name": "Guatemala",
    "capital": "Guatemala City",
    "region": "Americas",
    "subregion": "Central America",
    "tier": 2,
    "capitalQuestions": false
  },
  {
    "code": "GN",
    "name": "Guinea",
    "capital": "Conakry",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "GW",
    "name": "Guinea-Bissau",
    "capital": "Bissau",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 3,
    "capitalQuestions": false
  },
  {
    "code": "GY",
    "name": "Guyana",
    "capital": "Georgetown",
    "region": "Americas",
    "subregion": "South America",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "HT",
    "name": "Haiti",
    "capital": "Port-au-Prince",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "HN",
    "name": "Honduras",
    "capital": "Tegucigalpa",
    "region": "Americas",
    "subregion": "Central America",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "HU",
    "name": "Hungary",
    "capital": "Budapest",
    "region": "Europe",
    "subregion": "Central Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "IS",
    "name": "Iceland",
    "capital": "Reykjavik",
    "region": "Europe",
    "subregion": "Northern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "IN",
    "name": "India",
    "capital": "New Delhi",
    "region": "Asia",
    "subregion": "Southern Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "ID",
    "name": "Indonesia",
    "capital": "Jakarta",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "IR",
    "name": "Iran",
    "capital": "Tehran",
    "region": "Asia",
    "subregion": "Southern Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "IQ",
    "name": "Iraq",
    "capital": "Baghdad",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "IE",
    "name": "Ireland",
    "capital": "Dublin",
    "region": "Europe",
    "subregion": "Northern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "IL",
    "name": "Israel",
    "capital": "Jerusalem",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": false
  },
  {
    "code": "IT",
    "name": "Italy",
    "capital": "Rome",
    "region": "Europe",
    "subregion": "Southern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "JM",
    "name": "Jamaica",
    "capital": "Kingston",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "JP",
    "name": "Japan",
    "capital": "Tokyo",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "JO",
    "name": "Jordan",
    "capital": "Amman",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "KZ",
    "name": "Kazakhstan",
    "capital": "Astana",
    "region": "Asia",
    "subregion": "Central Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "KE",
    "name": "Kenya",
    "capital": "Nairobi",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "KI",
    "name": "Kiribati",
    "capital": "South Tarawa",
    "region": "Oceania",
    "subregion": "Micronesia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "KW",
    "name": "Kuwait",
    "capital": "Kuwait City",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": false
  },
  {
    "code": "KG",
    "name": "Kyrgyzstan",
    "capital": "Bishkek",
    "region": "Asia",
    "subregion": "Central Asia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "LA",
    "name": "Laos",
    "capital": "Vientiane",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "LV",
    "name": "Latvia",
    "capital": "Riga",
    "region": "Europe",
    "subregion": "Northern Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "LB",
    "name": "Lebanon",
    "capital": "Beirut",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "LS",
    "name": "Lesotho",
    "capital": "Maseru",
    "region": "Africa",
    "subregion": "Southern Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "LR",
    "name": "Liberia",
    "capital": "Monrovia",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "LY",
    "name": "Libya",
    "capital": "Tripoli",
    "region": "Africa",
    "subregion": "Northern Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "LI",
    "name": "Liechtenstein",
    "capital": "Vaduz",
    "region": "Europe",
    "subregion": "Western Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "LT",
    "name": "Lithuania",
    "capital": "Vilnius",
    "region": "Europe",
    "subregion": "Northern Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "LU",
    "name": "Luxembourg",
    "capital": "Luxembourg",
    "region": "Europe",
    "subregion": "Western Europe",
    "tier": 2,
    "capitalQuestions": false
  },
  {
    "code": "MG",
    "name": "Madagascar",
    "capital": "Antananarivo",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "MW",
    "name": "Malawi",
    "capital": "Lilongwe",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "MY",
    "name": "Malaysia",
    "capital": "Kuala Lumpur",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "MV",
    "name": "Maldives",
    "capital": "Malé",
    "region": "Asia",
    "subregion": "Southern Asia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "ML",
    "name": "Mali",
    "capital": "Bamako",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "MT",
    "name": "Malta",
    "capital": "Valletta",
    "region": "Europe",
    "subregion": "Southern Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "MH",
    "name": "Marshall Islands",
    "capital": "Majuro",
    "region": "Oceania",
    "subregion": "Micronesia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "MR",
    "name": "Mauritania",
    "capital": "Nouakchott",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "MU",
    "name": "Mauritius",
    "capital": "Port Louis",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "MX",
    "name": "Mexico",
    "capital": "Mexico City",
    "region": "Americas",
    "subregion": "North America",
    "tier": 1,
    "capitalQuestions": false
  },
  {
    "code": "FM",
    "name": "Micronesia",
    "capital": "Palikir",
    "region": "Oceania",
    "subregion": "Micronesia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "MD",
    "name": "Moldova",
    "capital": "Chișinău",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "MC",
    "name": "Monaco",
    "capital": "Monaco",
    "region": "Europe",
    "subregion": "Western Europe",
    "tier": 2,
    "capitalQuestions": false
  },
  {
    "code": "MN",
    "name": "Mongolia",
    "capital": "Ulaanbaatar",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "ME",
    "name": "Montenegro",
    "capital": "Podgorica",
    "region": "Europe",
    "subregion": "Southeast Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "MA",
    "name": "Morocco",
    "capital": "Rabat",
    "region": "Africa",
    "subregion": "Northern Africa",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "MZ",
    "name": "Mozambique",
    "capital": "Maputo",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "MM",
    "name": "Myanmar",
    "capital": "Naypyidaw",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "NA",
    "name": "Namibia",
    "capital": "Windhoek",
    "region": "Africa",
    "subregion": "Southern Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "NR",
    "name": "Nauru",
    "capital": "Yaren",
    "region": "Oceania",
    "subregion": "Micronesia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "NP",
    "name": "Nepal",
    "capital": "Kathmandu",
    "region": "Asia",
    "subregion": "Southern Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "NL",
    "name": "Netherlands",
    "capital": "Amsterdam",
    "region": "Europe",
    "subregion": "Western Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "NZ",
    "name": "New Zealand",
    "capital": "Wellington",
    "region": "Oceania",
    "subregion": "Australia and New Zealand",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "NI",
    "name": "Nicaragua",
    "capital": "Managua",
    "region": "Americas",
    "subregion": "Central America",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "NE",
    "name": "Niger",
    "capital": "Niamey",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "NG",
    "name": "Nigeria",
    "capital": "Abuja",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "KP",
    "name": "North Korea",
    "capital": "Pyongyang",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "MK",
    "name": "North Macedonia",
    "capital": "Skopje",
    "region": "Europe",
    "subregion": "Southeast Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "NO",
    "name": "Norway",
    "capital": "Oslo",
    "region": "Europe",
    "subregion": "Northern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "OM",
    "name": "Oman",
    "capital": "Muscat",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "PK",
    "name": "Pakistan",
    "capital": "Islamabad",
    "region": "Asia",
    "subregion": "Southern Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "PW",
    "name": "Palau",
    "capital": "Ngerulmud",
    "region": "Oceania",
    "subregion": "Micronesia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "PA",
    "name": "Panama",
    "capital": "Panama City",
    "region": "Americas",
    "subregion": "Central America",
    "tier": 2,
    "capitalQuestions": false
  },
  {
    "code": "PG",
    "name": "Papua New Guinea",
    "capital": "Port Moresby",
    "region": "Oceania",
    "subregion": "Melanesia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "PY",
    "name": "Paraguay",
    "capital": "Asunción",
    "region": "Americas",
    "subregion": "South America",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "PE",
    "name": "Peru",
    "capital": "Lima",
    "region": "Americas",
    "subregion": "South America",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "PH",
    "name": "Philippines",
    "capital": "Manila",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "PL",
    "name": "Poland",
    "capital": "Warsaw",
    "region": "Europe",
    "subregion": "Central Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "PT",
    "name": "Portugal",
    "capital": "Lisbon",
    "region": "Europe",
    "subregion": "Southern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "QA",
    "name": "Qatar",
    "capital": "Doha",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "CG",
    "name": "Republic of the Congo",
    "capital": "Brazzaville",
    "region": "Africa",
    "subregion": "Middle Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "RO",
    "name": "Romania",
    "capital": "Bucharest",
    "region": "Europe",
    "subregion": "Southeast Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "RU",
    "name": "Russia",
    "capital": "Moscow",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "RW",
    "name": "Rwanda",
    "capital": "Kigali",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "KN",
    "name": "Saint Kitts and Nevis",
    "capital": "Basseterre",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "LC",
    "name": "Saint Lucia",
    "capital": "Castries",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "VC",
    "name": "Saint Vincent and the Grenadines",
    "capital": "Kingstown",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "WS",
    "name": "Samoa",
    "capital": "Apia",
    "region": "Oceania",
    "subregion": "Polynesia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "SM",
    "name": "San Marino",
    "capital": "City of San Marino",
    "region": "Europe",
    "subregion": "Southern Europe",
    "tier": 2,
    "capitalQuestions": false
  },
  {
    "code": "ST",
    "name": "São Tomé and Príncipe",
    "capital": "São Tomé",
    "region": "Africa",
    "subregion": "Middle Africa",
    "tier": 3,
    "capitalQuestions": false
  },
  {
    "code": "SA",
    "name": "Saudi Arabia",
    "capital": "Riyadh",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "SN",
    "name": "Senegal",
    "capital": "Dakar",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "RS",
    "name": "Serbia",
    "capital": "Belgrade",
    "region": "Europe",
    "subregion": "Southeast Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "SC",
    "name": "Seychelles",
    "capital": "Victoria",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "SL",
    "name": "Sierra Leone",
    "capital": "Freetown",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "SG",
    "name": "Singapore",
    "capital": "Singapore",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "tier": 2,
    "capitalQuestions": false
  },
  {
    "code": "SK",
    "name": "Slovakia",
    "capital": "Bratislava",
    "region": "Europe",
    "subregion": "Central Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "SI",
    "name": "Slovenia",
    "capital": "Ljubljana",
    "region": "Europe",
    "subregion": "Central Europe",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "SB",
    "name": "Solomon Islands",
    "capital": "Honiara",
    "region": "Oceania",
    "subregion": "Melanesia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "SO",
    "name": "Somalia",
    "capital": "Mogadishu",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "ZA",
    "name": "South Africa",
    "capital": "Pretoria",
    "region": "Africa",
    "subregion": "Southern Africa",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "KR",
    "name": "South Korea",
    "capital": "Seoul",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "SS",
    "name": "South Sudan",
    "capital": "Juba",
    "region": "Africa",
    "subregion": "Middle Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "ES",
    "name": "Spain",
    "capital": "Madrid",
    "region": "Europe",
    "subregion": "Southern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "LK",
    "name": "Sri Lanka",
    "capital": "Sri Jayawardenepura Kotte",
    "region": "Asia",
    "subregion": "Southern Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "SD",
    "name": "Sudan",
    "capital": "Khartoum",
    "region": "Africa",
    "subregion": "Northern Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "SR",
    "name": "Suriname",
    "capital": "Paramaribo",
    "region": "Americas",
    "subregion": "South America",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "SE",
    "name": "Sweden",
    "capital": "Stockholm",
    "region": "Europe",
    "subregion": "Northern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "CH",
    "name": "Switzerland",
    "capital": "Bern",
    "region": "Europe",
    "subregion": "Western Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "SY",
    "name": "Syria",
    "capital": "Damascus",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "TJ",
    "name": "Tajikistan",
    "capital": "Dushanbe",
    "region": "Asia",
    "subregion": "Central Asia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "TZ",
    "name": "Tanzania",
    "capital": "Dodoma",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "TH",
    "name": "Thailand",
    "capital": "Bangkok",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "TL",
    "name": "Timor-Leste",
    "capital": "Dili",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "TG",
    "name": "Togo",
    "capital": "Lomé",
    "region": "Africa",
    "subregion": "Western Africa",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "TO",
    "name": "Tonga",
    "capital": "Nuku'alofa",
    "region": "Oceania",
    "subregion": "Polynesia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "TT",
    "name": "Trinidad and Tobago",
    "capital": "Port of Spain",
    "region": "Americas",
    "subregion": "Caribbean",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "TN",
    "name": "Tunisia",
    "capital": "Tunis",
    "region": "Africa",
    "subregion": "Northern Africa",
    "tier": 2,
    "capitalQuestions": false
  },
  {
    "code": "TR",
    "name": "Türkiye",
    "capital": "Ankara",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "TM",
    "name": "Turkmenistan",
    "capital": "Ashgabat",
    "region": "Asia",
    "subregion": "Central Asia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "TV",
    "name": "Tuvalu",
    "capital": "Funafuti",
    "region": "Oceania",
    "subregion": "Polynesia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "UG",
    "name": "Uganda",
    "capital": "Kampala",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "UA",
    "name": "Ukraine",
    "capital": "Kyiv",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "AE",
    "name": "United Arab Emirates",
    "capital": "Abu Dhabi",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "GB",
    "name": "United Kingdom",
    "capital": "London",
    "region": "Europe",
    "subregion": "Northern Europe",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "US",
    "name": "United States",
    "capital": "Washington D.C.",
    "region": "Americas",
    "subregion": "North America",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "UY",
    "name": "Uruguay",
    "capital": "Montevideo",
    "region": "Americas",
    "subregion": "South America",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "UZ",
    "name": "Uzbekistan",
    "capital": "Tashkent",
    "region": "Asia",
    "subregion": "Central Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "VU",
    "name": "Vanuatu",
    "capital": "Port Vila",
    "region": "Oceania",
    "subregion": "Melanesia",
    "tier": 3,
    "capitalQuestions": true
  },
  {
    "code": "VA",
    "name": "Vatican City",
    "capital": "Vatican City",
    "region": "Europe",
    "subregion": "Southern Europe",
    "tier": 2,
    "capitalQuestions": false
  },
  {
    "code": "VE",
    "name": "Venezuela",
    "capital": "Caracas",
    "region": "Americas",
    "subregion": "South America",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "VN",
    "name": "Vietnam",
    "capital": "Hanoi",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "tier": 1,
    "capitalQuestions": true
  },
  {
    "code": "YE",
    "name": "Yemen",
    "capital": "Sana'a",
    "region": "Asia",
    "subregion": "Western Asia",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "ZM",
    "name": "Zambia",
    "capital": "Lusaka",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 2,
    "capitalQuestions": true
  },
  {
    "code": "ZW",
    "name": "Zimbabwe",
    "capital": "Harare",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "tier": 2,
    "capitalQuestions": true
  }
];
